version: '3'

services:
    composer:
        image: composer
        container_name: composer
        environment:
            - COMPOSER_CACHE_DIR=/app/.cache/composer
        volumes:
            - .:/app
        #restart: never
    php:
        image: php:7.4-cli
        container_name: php
        #restart: never
        volumes:
            - .:/app
        working_dir: /app
    phpunit:
        image: php:7.4-cli
        container_name: phpunit
        #restart: never
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: vendor/bin/phpunit