# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  filecheck:
    name: Filecheck
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docdee/filecheck

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check linefeed is UNIX style only
        run:
          (! find . -maxdepth 1 -name "*.*" -not -type d -exec file "{}" ";" | grep "CRLF\|CR")

      - name: Check files are UTF8 only
        run:
          (find . -maxdepth 1 -name "*.*" -not -type d -exec isutf8 "{}" "+")

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer, phpunit

      - name: Composer stuff
        run: composer install --no-interaction --no-ansi --no-progress --working-dir=.

      - name: Check version of phpunit
        run: phpunit --version

      - name: Run test
        run: phpunit tests/*.php
